name: jeremyserver

services:
  vaultwarden:
    container_name: vaultwarden
    image: "vaultwarden/server:latest"
    restart: always
    user: 1001:1001
    depends_on:
      - authelia
    env_file: vaultwarden.env
    volumes:
      - "/mnt/oraclevdb/vaultwarden/:/data/"
    secrets:
      - source: vaultwarden-database-url
        uid: "1001"
        gid: "1001"

  rclone:
    container_name: rclone
    image: "rclone/rclone:latest"
    restart: always
    user: 1001:1001
    # Set main-bucket to name of bucket (oci_objectstorage_bucket.main.name)
    command: serve webdav oos:main-bucket --addr rclone:9800 --etag-hash auto --gid 1001 --htpasswd /run/secrets/htpasswd --uid 1001
    volumes:
      - "/mnt/oraclevdb/rclone/:/data/"
    configs:
      - source: rclone-config
        target: /config/rclone/rclone.conf
        uid: "1001"
        gid: "1001"
    secrets:
      - source: htpasswd
        uid: "1001"
        gid: "1001"

  robots-txt:
    container_name: robots-txt
    image: busybox
    restart: always
    user: "1001:1001"
    command: httpd -f -p 8008
    configs:
      - source: robots.txt
        uid: "1001"
        gid: "1001"
      - source: httpd-conf
        target: /etc/httpd.conf
        uid: "1001"
        gid: "1001"

  gatus:
    container_name: gatus
    image: ghcr.io/twin/gatus:latest
    restart: always
    user: 1001:1001
    depends_on:
      - vaultwarden
      - rclone
      - robots-txt
      - foldingathome
      - freshrss
      - authelia
      - wg-easy
    env_file:
      - gatus.env
    volumes:
      - "/mnt/oraclevdb/gatus/:/data/"
    configs:
      - source: gatus-config
        target: /config/config.yaml
        uid: "1001"
        gid: "1001"

  cloudflared:
    container_name: cloudflared
    image: "cloudflare/cloudflared:latest"
    restart: always
    depends_on:
      - vaultwarden
      - rclone
      - robots-txt
      - gatus
      - freshrss
      - authelia
      - wg-easy
    volumes:
      - "/mnt/oraclevdb/cloudflared:/user/nonroot/.cloudflared/"
    command: tunnel run
    configs:
      - source: cloudflared-config
        target: /etc/cloudflared/config.yml
        uid: "65532"
        gid: "65532"
        mode: 0400
    secrets:
      - source: cloudflared-credentials-file
        target: credentials-file.json
        uid: "65532"
        gid: "65532"
        mode: 0400

  foldingathome:
    container_name: foldingathome
    image: lscr.io/linuxserver/foldingathome:latest
    restart: always
    environment:
      PUID: 1001
      PGID: 1001
      TZ: America/Los_Angeles
      CLI_ARGS: "--config /run/configs/config.xml"
    volumes:
      - /mnt/oraclevdb/foldingathome:/config/
    configs:
      - source: fah-config
        target: /run/configs/config.xml
        uid: "1001"
        gid: "1001"

  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:latest
    restart: always
    depends_on:
      - authelia
    env_file: ./freshrss.env
    volumes:
      - /mnt/oraclevdb/freshrss/:/var/www/FreshRSS/data/
    configs:
      - source: opml-xml
        target: /var/www/FreshRSS/data/opml.xml
        uid: "33"
        gid: "33"

  authelia:
    container_name: authelia
    image: "authelia/authelia:latest"
    restart: always
    env_file: ./authelia.env
    volumes:
      - "./users_database.yml:/config/users_database.yml"
      - "/mnt/oraclevdb/authelia/:/config/"
    configs:
      - source: authelia-config
        target: /config/configuration.yml
        uid: "1001"
        gid: "1001"
    secrets:
      [
        "jwt-secret",
        "session-secret",
        "storage-encryption-key",
        "hmac-secret",
        "authelia-oidc-signing-key",
        "authelia-redis-password",
      ]

  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:edge
    restart: always
    depends_on:
      - authelia
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
    env_file: ./wg-easy.env
    volumes:
      - /mnt/oraclevdb/wireguard/:/etc/wireguard/
    ports:
      - 51820:51820/udp

  redis:
    container_name: redis
    image: redis:8
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /mnt/oraclevdb/redis/:/data/
    configs:
      - source: redis-config
        target: /usr/local/etc/redis/redis.conf
        uid: "999"
        gid: "999"
    secrets:
      - source: redis-users-acl
        target: /usr/local/etc/redis/users.acl
        uid: "999"
        gid: "999"

configs:
  rclone-config:
    file: ./rclone.conf
  httpd-conf:
    # https://git.busybox.net/busybox/tree/networking/httpd.c
    content: I:robots.txt
  robots.txt:
    content: |
      User-agent: *
      Disallow: /
  gatus-config:
    file: ./gatus-config.yaml
  opml-xml:
    file: ./opml.xml
  cloudflared-config:
    file: ./cloudflare.config.yml
  fah-config:
    file: ./fah.config.xml
  authelia-config:
    file: ./authelia.configuration.yml
  redis-config:
    file: ./redis.conf

secrets:
  vaultwarden-database-url:
    file: ./vaultwarden-database-url
  htpasswd:
    file: ./htpasswd
  cloudflared-credentials-file:
    file: ./cloudflared-credentials-file.json
  jwt-secret:
    file: "./jwt-secret"
  session-secret:
    file: "./session-secret"
  hmac-secret:
    file: "./hmac-secret"
  storage-encryption-key:
    file: "./storage-encryption-key"
  authelia-oidc-signing-key:
    file: "./authelia-oidc-signing-key"
  authelia-redis-password:
    file: "./authelia-redis-password"
  redis-users-acl:
    file: "./redis.users.acl"
