# Network
bind 0.0.0.0
protected-mode no
port 6379
tcp-keepalive 300

# Snapshotting
save 900 1
save 300 10
save 60 10000

# Security
aclfile /usr/local/etc/redis/users.acl

# Memory management
maxmemory 256mb
maxmemory-policy allkeys-lru

# Append only Mode
appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# General
loglevel notice
